pycalphad/pycalphad

.travis.yml
appveyor.yml
pycalphad/io/database.py
pycalphad/tests/test_database.py

**Please check that I updated the Travis and Appveyor files correctly.** 
Closes gh-66.
Add Python 3.6 to Travis and Appveyor
Python 3.6 changed `splitext` to support path-like objects, so passing a StringIO
(file-like) now throws a `TypeError` instead of an `AttributeError`. This was
changed at 3 instances in the format determination.
A test was also written to check that passing a StringIO directly to the Database
constructor (e.g. not using the static method constructors) will proceed
correctly through the try-except block. It's the same test as from_file, it just
did not exist for the direct __new__ constructor.

BLD/TST: Add support for Python 3.6

---

pycalphad/core/custom_autowrap.py

Compiler settings on certain machines can create files such as debug
symbols. This commit creates a blacklist for filtering those files out,
leaving only the compiled file. We cannot more directly find the compiled
file because only the extensions differ (e.g. '*.so' and '*.so.dysm') and
the extensions of the compiled files change on different platforms.
Fixes gh-65

FIX: Create a blacklist for compiler files

---

pycalphad/io/database.py
pycalphad/io/tdb.py
pycalphad/tests/test_database.py
pycalphad/tests/test_model.py

This limitation and other limitations as a subset of the different TDB implementations should be handled by pycalphad so that any output database can work on any thermodynamics software. Some of these limitations can be handled automatically, as in the case of line length limits, others cannot. These changes typically break `DB == DB.read(DB.write())`, so they require explicit handling from the user. 
Here, Thermo-Calc TDBs require symbols to be <= 8 characters
This PR:
- Provides a reasonably scalable (rough) framework to optionally sanitize TDBs for compatibility with the following options in the case of an invalid database
- 'raise' (default): raise an error if the TDB is invalid and cannot be automatically compatible 
- 'warn': Issue a warning that the database is invalid and write it …

TC TDB Compatibility (symbol length)

---

LICENSE.txt

This is a license year bump and adds @bocklund as an identified contributor to the project. (My employer, Caltech, is also added to the copyright notice, per a software release agreement.)
It's probably a good idea to get @bocklund on record that, while he retains the copyright over his own contributions (no CLA), he is aware that all of his contributions are made to the project under the terms of the MIT license. Do you consent to this?

DOC: Update license

---

pycalphad/core/eqsolver.pyx
pycalphad/plot/eqplot.py

As discussed in #4, conditions where the total composition is > 1 should be skipped, but instead were referencing the `phases` variable which does not exist.
Also a small fix some duplicate code in `eqplot` is included because line 58 ensures that `ax` will never be `None` here.

Fix filtering of phases with composition >1

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

Thermo-Calc will not parse commands or other strings after the command delimiter. Previously pycalphad only removed comments after command delimiters. This commit makes pycalphad conform  to the behavior of parsing out everything on the line after the delimiter and includes a test for this behavior.
Another approach might be to only strip characters after the last delimiter on a line, which would be an overall improved approach in the case that multiple commands were on a single line (or an entire TDB on a single line) even though I have never encountered such a case in the wild. I'm not sure how other commercial software handles multiple commands per line.

ENH: TDB compatibility: all chars after command delimiters should be neglected

---

pycalphad/core/equilibrium.py
pycalphad/tests/test_database.py
pycalphad/tests/test_equilibrium.py

Closes #52 
- Calling equilibrium() with keyword arguments that are unused raises a UserWarning
- Includes a test for the behavior
- removes outdated progress bar API in test suite
- Changes other tests for warnings to assert that `len(warnings) == 1` rather than `len(warnings) > 0` in case we add new warnings in the future that could cause test to falsely pass

Warn when unused keyword arguments are passed to equilibrium

---

pycalphad/core/sympydiff_utils.py

This fixes an issue with some unpublished custom Models reported by a user to have issues when using `calculate` to compute a property besides `GM` (e.g., `CPM`), where that property's symbolic derivative can generate `zoo` (complex infinity) or the constant `PI`.
@bocklund This is a quick fix designed to be pushed into a new minor release. (A better fix would fix the code generation side rather than search-and-replace the SymPy object.) There is a workshop next week where the user's work will prominently feature pycalphad, and we want to make sure the calculations run.

FIX: sympydiff_utils: Replace some constants to ensure compilation

---

pycalphad/tests/test_database.py
pycalphad/tests/test_equilibrium.py

Warning testing is independent of the number of warnings raised and depends instead on specific string fragments.

FIX: Improve tests that check warnings.

---

pycalphad/core/custom_autowrap.py
pycalphad/core/utils.py
pycalphad/tests/test_database.py
pycalphad/tests/test_energy.py
pycalphad/tests/test_equilibrium.py

FIX: sympy 1.1 compatibility

---

.travis.yml

See http://steven.casagrande.io/articles/travis-ci-and-if-statements/ and https://github.com/travis-ci/travis-ci/issues/1066
Since we currently don't have anything that would warrant continuing after a non-zero exit code, this solution is the simplest.
Closes #107

BLD/FIX: use `set -e` to to exit on failure of any command in travis build.

---

pycalphad/io/database.py
pycalphad/tests/test_database.py

Closes #94.
This handles cases where `if_exists` is passed a string that is not in ['raise', 'overwrite', 'rename']. In that case, we should raise rather than overwrite.

FIX: Database.write should raise if one of the specified values is not entered.

---

pycalphad/io/database.py
pycalphad/io/tdb.py
pycalphad/tests/test_database.py

Species in a TDB are parsed in the `Specie` class and added to the `species` set attribute of the Database.
The Specie class has several attributes:
- `name`: the name of the specie
- `constituents`: a dictionary of `{element: composition}` of the specie
- `charge`: integer charge. Defaults to zero if none specified.
As discussed in the Thermo-Calc database manager guide, elements entered via the ELEMENT command are automatically entered as species. We match that behavior here. The constituents of an element are just that element with a fraction of 1 and the charge is 0.
In principle, the constituents dictionary will be used in the solver to link the specie to how it contributes to the overall mass balance conditions.
Tests are included that test the basic functionality. I think the …

ENH: Species support in Database and TDB read/write

---

pycalphad/core/calculate.py
pycalphad/tests/test_calculate.py

Maintain sorted state variable ordering when one or more state variables is left as default. Fixes gh-116.

FIX: calculate: Maintain sorted state variable ordering

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

FIX: tdb: Update float parsing regex to detect floats with no trailing digits. Fixes gh-143.

FIX: tdb: Update float parsing regex

---

INSTALLING.rst
conda_recipe/meta.yaml
docs/api/pycalphad.core.rst
docs/api/pycalphad.io.rst
docs/api/pycalphad.plot.rst
docs/api/pycalphad.rst
docs/examples/BinaryExamples.rst
docs/examples/CementiteAnalysis.rst
docs/examples/TernaryExamples.rst
docs/examples/UsingCalculationResults.rst
docs/examples/index.rst
docs/faq.rst
docs/index.rst
examples/BinaryExamples.ipynb
examples/CementiteAnalysis.ipynb
examples/TernaryExamples.ipynb
examples/UsingCalculationResults.ipynb
pycalphad/__init__.py
pycalphad/core/equilibrium.py
setup.py

Fixes gh-126, fixes gh-128, fixes gh-134, and fixes gh-139
Regarding points in #126:
* Update installation to first suggest anaconda installation for all platforms. Also update the development mode, because conda-build is not well maintained for using development mode in environments. Suggested to use pip or setup.py in conda/conda-build#1992
This PR updates the installation guide with step by step instructions for all platforms, but emphasizing Anaconda. It is now more clear that you can use either distribution to install pycalphad. 
The installation includes the caveats of the Ipopt installation situation for pip installation and develop mode, as well as a Anaconda alternative to develop mode. 
* Add page describing parallelism with dask
This is in the newly added FAQ
* Estimate of …

Update installation and add FAQ. Handle warnings

---

pycalphad/core/equilibrium.py
pycalphad/core/utils.py
pycalphad/tests/test_equilibrium.py
pycalphad/tests/test_utils.py

Closes #100 and closes #129
I use this all the time. @richardotis what do you think about including this in pycalphad proper?
Any thoughts on doing this automatically in equilibrium calculations? That way users could always pass in phases=dbf.phases.keys() without getting any error messages. In large databases, your only other choice is to tediously select phases in the system you want to calculate.

ENH: Add a function to filter inactive phases

---

appveyor.yml
pycalphad/core/calculate.py
pycalphad/core/custom_autowrap.py
pycalphad/core/equilibrium.py
pycalphad/core/phase_rec.pyx
pycalphad/core/sympydiff_utils.py

The `Model` class is JIT-compiled by an autowrap-based utility, which is primarily located in `core\sympydiff_utils.py` and `core\custom_autowrap.py`. A substantial portion of the startup time for a new `Model` used in a calculation is in the JIT. Here the performance is improved via profiling, where redundant or unnecessary computations are eliminated. In particular, since the new IPOPT-based solver does not require direct Hessian computation, Hessian codegen is disabled. This, and a few other tweaks,lead to a 50-70% reduction in the first-run time for `Model`-based computations.

ENH: JIT performance improvement

---

pycalphad/core/equilibrium.py

Compute degrees of freedom correctly when only a subset of constituents in a phase's sublattice model are used in a calculation. Fixes gh-159.
@bocklund Do you think it needs a test?

FIX: eqcalculate: Property calculation for "partially loaded" phase models

---

pycalphad/core/custom_autowrap.py
pycalphad/core/sympydiff_utils.py

- Callable module names/ids were modified in custom_autowrap.wrap_code function.
- sympydiff_utils was not properly getting a pointer to the name of the C routine

FIX: Fix compiling+autowrapping of Model callables

---

pycalphad/tests/test_variables.py
pycalphad/variables.py

FIX: fix Species Python 2 unicode support

---

pycalphad/core/calculate.py

For a set of 30M points (x16 DOF = 500M array elements), `calculate` had an overhead of ~35s beyond calling the objective function. These changes optimize that down to ~13s in the general case and ~5s in special cases.
When working with a large (8 sublattice) binary system, which results in points arrays of approximately 500M points at a point density of 1000. calling calculate was very slow.
This PR introduces some optimizations to speed up calculate.
For reference, here is the script that was run:
```python
from pycalphad import calculate, Database
dbf = Database('/Users/brandon/Projects/notebooks/pycalphad/AB8SL_v4.TDB')
from pycalphad import Model
mod = Model(dbf, ['A', 'B'], 'FCC')  # save time initializing models on each call
calc_res = calculate(dbf, ['A', 'B'], 'FCC', pdens=1000, …
```

ENH: Optimize calculate

---

conda_recipe/meta.yaml
pycalphad/__init__.py
pycalphad/core/custom_autowrap.py
pycalphad/core/patched_piecewise.py
setup.py

Provides compatibility fixes for codegen changes, as well as a workaround for sympy/sympy#14933

SymPy 1.2 compatibility

---

pycalphad/core/phase_rec.pyx

FIX: PhaseRecord: Pickled memoryviews are wrapped in calls to np.array()

---

.travis.yml
ci/travis_legacy_deps.sh
pycalphad/codegen/callables.py
pycalphad/codegen/sympydiff_utils.py
pycalphad/core/calculate.py
pycalphad/core/constants.py
pycalphad/core/constraints.py
pycalphad/core/eqsolver.pyx
pycalphad/core/hyperplane.pxd
pycalphad/core/hyperplane.pyx
pycalphad/core/lower_convex_hull.py
pycalphad/core/phase_rec.pxd
pycalphad/core/phase_rec.pyx
pycalphad/core/problem.pyx
pycalphad/core/solver.py
pycalphad/core/starting_point.py
pycalphad/tests/test_equilibrium.py

This PR adds a new, flexible constraint system via JIT-compiled functions. This new flexibility is used to add support for chemical potentials as conditions in an equilibrium calculation.

WIP: Chemical potential conditions support

---

pycalphad/codegen/callables.py
pycalphad/core/calculate.py
pycalphad/core/constraints.py
pycalphad/core/equilibrium.py
pycalphad/core/utils.py
pycalphad/model.py
pycalphad/tests/test_calculate.py
pycalphad/tests/test_equilibrium.py
pycalphad/variables.py

The following changes are made:
1. `build_callables` now becomes `build_callables` and `build_phase_records`. 
- Both require that correctly instantated model dicts, i.e. {'PHASE_NAME': Model()}
- `build_callables` should be called by users and just builds the callable functions and JIT compiles them. It returns a dict of `{'output': {'callables': {'PHASE_NAME': AutowrapFunc()}, 'massfuncs': {'PHASE_NAME': AutowrapFunc()}, ...}}`. These callables are passed to equilibrium and calculate.
- Calculate and equilibrium should be calling `build_phase_records`, which optionally take `callables`. If callables are provided for the output, they are not recomputed (if users pass callables, they are responsible for determine if they are compatible). If no callables are passed, compatible ones will be …

MAINT: Refactor build_callables

---

pycalphad/core/calculate.py
pycalphad/core/utils.py
pycalphad/tests/test_utils.py

Two changes here:
1. `instantiate_models` now returns a dict instead of a default dict to be more explicit. Only phases passed to `instantiate_models` are included.
2. Fixed a subtle bug in calculate where over-specified models could have led to inconsistent maximum internal degree of freedom between `calculate` and `starting_point` because `calculate` based the internal dof size on all the model instances, while starting_point used the phase records (active phases only).

FIX: Improve Model instantiation

---

conda_recipe/meta.yaml
setup.py

Relax dask requirements to the minimum required for `scheduler=` syntax

MAINT: Relax dask requirements

---

pycalphad/model.py

Profiling showed that a significant amount of time is spent building reference models. This code puts the code to build_reference_models behind a property, which speeds up the test suite by about 30% based on my tests.

MAINT/TST: Put build_reference_model behind a property

---

pycalphad/core/cache.py
pycalphad/core/utils.py
pycalphad/io/tdb.py
pycalphad/tests/test_database.py

Fixes gh-233 and fixes gh-231.
This also addresses the deprecation of `inspect.getargspec` in Python 3, as well as a reorganization of the `collections` standard library module set to go into effect in Python 3.8.
For future error reporting, the TDB parser will include some details about the line in the TDB file which caused any exception, regardless of whether it is a syntax mistake in the TDB file (`ParseException`) or a bug further up the stack.

FIX: SymPy namespace clash with TDBs, and other deprecation fixes

---

pycalphad/model.py
pycalphad/tests/datasets.py
pycalphad/tests/test_model.py

Bugfix to detect phases containing pure vacancy sublattices, according to: https://github.com/pycalphad/pycalphad/issues/191
When any phase satisfies the requirement (containing at least one pure vacancy sublattice) an error message is raised.

FIX: pure vacancy phase detection

---

INSTALLING.rst

Installation instructions are updated to:
1. Include details on installing the C/C++ compilers from conda-forge (for development versions)
2. Add instructions for updating the development version code or switching branches
3. Remove PyPI installation instructions because it's strongly discouraged and not officially supported.

DOC: Update installation instructions

---

.travis.yml
appveyor.yml
pycalphad/tests/test_energy.py

This PR updates 
* Travis CI's installation of the testing dependencies to use conda rather than pip, avoiding an issue where Python 3.6 failed to install the certifi package
* Appveyor's `pytest` call to correctly return the error code from the `pytest.main` function. Previously, the Python script exited at the end of the command with a successful error code, regardless of the status of the test suite.
The behavior was verified by writing a dummy `assert 1 == 2` test that caused all tests to fail (ade9aca), then removing that test to observe all tests succeeded (4a80675).

TST: CI maintenance

---

pycalphad/core/calculate.py
pycalphad/core/equilibrium.py
pycalphad/core/utils.py
pycalphad/tests/test_utils.py

Fixing the bug presented at https://github.com/pycalphad/pycalphad/issues/247
A new function `check_order_disorder` is now responsible to exclude the disordered phases when its respective ordered phase are active.
Some tests in `test_utils` had to be slightly changed, to run the new function `check_order_disorder` to remove the disordered phases when active phases are active.

FIX: Calculating disordered phase only if respective ordered phase inactive

---

.travis.yml
pycalphad/core/cache.py
pycalphad/core/calculate.py
pycalphad/core/equilibrium.py
pycalphad/core/halton.py
pycalphad/core/lower_convex_hull.py
pycalphad/core/solver.py
pycalphad/core/utils.py
pycalphad/io/database.py
pycalphad/io/tdb.py
pycalphad/model.py
pycalphad/tests/test_calculate.py
pycalphad/tests/test_database.py
pycalphad/tests/test_model.py
pycalphad/variables.py
setup.py

Accoring to the [Python 3.8 `ast` docs](https://docs.python.org/3.8/library/ast.html?highlight=ast#module-ast):
> Deprecated since version 3.8: Class ast.Constant is now used for all constants. Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases.
The tdb.py module whitelists certain `ast` objects, including `ast.Num`, which are now `ast.Constant`, causing breakages in sympifying parsed strings. This adds `ast.Constant` to our whitelist.
Thanks @jwsiegel2510 for pointing this out at https://github.com/PhasesResearchLab/ESPEI/pull/110
As an aside: this is an interesting breakage because `ast.Num` still exists in Python 3.8, but instantiating an `ast.Num` actually gives you an `ast.Constant` …

FIX: Fix Python 3.8 deprecation of ast.Num in favor of ast.Constant

---

conda_recipe/meta.yaml
pycalphad/io/tdb.py
setup.py

SymPy 1.5 release candidate 1 is out now. There is one breakage: EmptySet is now a singleton instead of a class ([see release notes](https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5#backwards-compatibility-breaks-and-deprecations) ).
Here is the simplest change. We also need to bump the requirements to pin sympy>=1.5.
There are a couple other options for changes:
1. Current change, use the singleton comparison instead of the class
2. Use the `.is_EmptySet` property, which is now deprecated in favor of the `.is_empty` property. Allows us to stay backwards compatible until the deprecated code is removed (https://github.com/sympy/sympy/issues/17523)
3. Use the `.is_empty` property, which would still require bumping the version to sympy>=1.5
Staying with comparing to the singleton …

MAINT: SymPy 1.5 compatibility

---

pycalphad/core/equilibrium.py
pycalphad/core/starting_point.py
pycalphad/io/database.py
pycalphad/model.py
pycalphad/plot/binary/compsets.py
pycalphad/plot/binary/map.py
pycalphad/plot/eqplot.py
pycalphad/plot/ternary.py
pycalphad/tests/test_variables.py
pycalphad/variables.py

**Opening this PR for feedback.**
I sketched out example implementations of MassFraction and Composition objects (the old Composition object was refactored to MoleFraction).
MassFraction objects are basically sister objects to MoleFraction, just using `W` instead of `X`. 
Composition objects are convenience objects that would describe a complete composition for a system as would be used in a calculation. The key ideas of a Composition are
1. All Compositions are single point compositions. 
a. Any mixing, broadcasting, or paths between Composition objects are not Compositions themselves, but simply dicts mapping v.X or v.W to a float, tuple, or array, as in the equilibrium API.
b. The Composition object could be a platform to create such dictionaries, but are fundamentally *not* those …

ENH: variables.MassFraction and variables.Composition object implementations

---

.github/pull_request_template.md
.travis.yml
RELEASING.rst
appveyor.yml
pycalphad/codegen/sympydiff_utils.py
pycalphad/core/constraints.py
pycalphad/core/phase_rec.pxd
pycalphad/core/phase_rec.pyx
pycalphad/tests/test_codegen.py
pycalphad/tests/test_utils.py
setup.py

This PR includes the following changes:
1. PhaseRecords can now be pickled, provided that all callables are built with LLVM callables. This is from adding internal references (e.g. `ofunc_` to to callable functions that are pickled and reused to create the `FastFunction` objects when unpickling.
2. LLVM callables are now the default everywhere, but this can be configured at runtime or through the `build_functions` or `build_constraint_functions` function APIs.
3. Improved module documentation for `sympydiff_utils` and `build_functions`/`build_constraint_functions`.
4. Updates to pin to `symengine=0.6`. This drastically improves the compile time performance for some of the worst-case systems and makes the compile times go from impossible on LLVM (>20,000 sec) to possible (~30-60 sec).
5. …

FIX: Support PhaseRecord pickling, switch SymEngine backend to LLVM (configurable)

---

pycalphad/io/database.py
pycalphad/io/tdb.py

I noticed `Database('steel_database_fix.tdb')` can take a long time to complete, 40-90 seconds depending on the machine. Switching to tinydb's `insert_multiple` API is a cheap and easy way to cut that time in ~half.
Most of the remaining time is in parsing the grammar for all the PARAMETERs, as well as calls to sympify for the function expressions. There's room to improve there (may be possible to get the time down to ~6 seconds), but those changes may break some internal or external APIs and will be more complicated to implement. This is the low-hanging fruit.

ENH: Reading large databases

---

pycalphad/core/equilibrium.py
pycalphad/core/utils.py

When the Phase is defined in a Database with many more components than are defined
to be active in the present calculation, `_eqcalculate()` would incorrectly calculate degrees of freedom based on all possible components, instead of the active ones.
This would then lead to errors inside `calculate()`, when the length of the passed `points` array would exceed the `maximum_internal_dof`.
This fix does two things:
1. Calculates degrees of freedom using the already-passed `models` object, which is based on the active components.
2. Fixes `unpack_phases` to return only the active phases, instead of returning nothing and causing a fallback to all phases in the Database. (This wasn't a correctness issue, but it did cause unnecessary computation.)

FIX: eqcalculate: Calculate degrees of freedom based on Model

---

pycalphad/core/equilibrium.py

In reviewing #270, I overlooked the fact that `calculate` takes the argument `model`, which a caller could pass as a keyword argument to `_eqcalculate`. #270 changed `_eqcalculate` to explicitly take a `models` argument and pass it to `calculate`.
This preserves the behavior from #270 and stays backwards compatible if anyone was using `model` as a keyword argument that got passed through to `calculate`.

FIX: _eqcalculate: Rename `models` -> `model` for backwards compatibility

---

pycalphad/model.py

This PR changes how Redlich-Kister sums are constructed within the `Model` object. Currently all parameters read from the TDB file are wrapped in upper and lower temperature bounds, which in `Model` are represented by a SymPy `Piecewise` object. This is true even when there is only a single nonzero branch for the parameter. It turns out that when such `Piecewise` objects are propagated through complex models like the magnetic ordering model, the automatically-generated first and second derivatives will have a very large number of "zero-terms" corresponding to entries outside the temperature limits. In some cases this can even cause memory errors or slowdowns for multi-component systems.
In this fix, we simply choose to extrapolate beyond the temperature limits by removing the single …

Model: redlich_kister_sum: Unwrap Piecewise with trivial branches

---

pycalphad/io/database.py
pycalphad/plot/eqplot.py

In 2D phase diagrams, 2D three phase regions (and tie-triangles) can only exist in where two molar quantities are axis variables. A binary temperature-composition phase diagram can only have three phases exist on an invariant line that occurs at an infinitesimally small temperature. In a binary system under fixed pressure, temperature and composition conditions, it _should_ be impossible to find three phases in equilibrium, however numerically it is possible to achieve three phase stability within pycalphad's convergence limits under these conditions.
`eqplot` only supports T-X binary phase diagrams and X-X ternary isothermal phase diagrams, and implicitly assumes that all three phase equilibria belong to a three phase region in a isothermal phase diagram. If three phases were found to be …

FIX: Fix eqplot for tie-triangles 

---

.github/workflows/test.yaml
README.rst
environment-dev.yml

Would supersede #293 if successful. Uses one `test.yaml` workflow for GitHub Actions that triggers on pull requests and pushes. We now use codecov.io for coverage on pushes and PRs (since coveralls does not support coverage from PRs, as discussed in #285).
This PR
- Introduces the codecov.io GitHub Action
- Switches the readme badge to use codecov instead of coveralls
- Drops coveralls dependency from `environment-dev.yml`

TST: Enable Codecov in a unified test YAML

---

pycalphad/plot/binary/plot.py
pycalphad/plot/binary/zpf_boundary_sets.py
pycalphad/plot/eqplot.py

Permit color and legend customization

---

INSTALLING.rst
environment-dev.yml
setup.py

Checklist
[cyipopt is now building on conda-forge for Windows](https://github.com/conda-forge/cyipopt-feedstock/pull/26) (thanks @moorepants!) so pycalphad does not require the pycalphad package anymore.
This PR 
- bumps pycalphad's dependency on cyipopt to v0.3 or later (the version required for Windows support)
- removes the pycalphad channel from the installation instructions.
Since this PR updates the installation instructions, we should not merge it until https://github.com/conda-forge/pycalphad-feedstock/pull/33 is merged and the package has propagated to the conda-forge channel.

MAINT: Drop pycalphad conda channel

---

.github/workflows/test.yaml
setup.py

Checklist
This PR
- Adds Python 3.9 to setup.py metadata
- Turns on Python 3.9 in our GitHub Actions CI

MAINT/CI: Support Python 3.9

---

pycalphad/plot/eqplot.py
pycalphad/plot/triangular.py

This PR houses a few changes, all in the `TriangluarAxes` projection class.
1. simplification of the transformations code
2. stop calling classmethods of `Axes` and passing self
3. fix several methods, such as `get_xaxis_text1_transform`, to call the superclass and get the transform *after* padding. This means setting the padding of the ticks and axis labels now works correctly for both axes.
4. add an override to `set_ylabel` that sets a default rotation of 60 degrees

FIX: Improve Triangular axes projection

---

pycalphad/core/calculate.py

Closes #322. 
This PR:
- Removes `_generate_fake_points`
- Removes some unused imports
- Alphabetizes imports and merged the `pycalphad.core.utils` imports

MAINT: Remove dead code from `calculate`

---

.github/workflows/test.yaml
environment-dev.yml
pycalphad/core/solver.py
setup.py

Checklist
This PR:
- Bumps versions on cyipopt, symengine, python-symengine and sympy
- Updates API of cyipopt for >1.0
- Adds `pip check` to the Test GitHub Action to try to protect against inconsistent dependencies between `setup.py` and those installed by `environment-dev.yml`

MAINT: Bump cyipopt to support new package name and v1.0 API; bump SymPy and SymEngine

---

pyproject.toml
setup.py

Checklist
This PR:
- Uses setuptools `setup_requires` to specify that pycalphad has build-time dependences on numpy, scipy and Cython.
- No longer raises import errors in `setup.py` when these packages are missing (the build tool should install them automatically)
Closes #309.

BLD: Use `setup_requires` for build Python build dependences

---

pycalphad/io/tdb.py

This PR fixes a regression introduced in #308 where the reference key in TDB `FUNCTION` and `PARAMETER` lines was limited to alpha numeric characters. Now `:_-` characters as well to fix some local databases that fail to parse. It's unclear what other valid characters could be. Thermo-Calc gives an example in the documentation including `REF:250`, `REF_002`, or `REF-SGTE`, so at least those are confirmed valid characters.
On my on the 522 local TDB files, this dropped the parse failures from 41 to 14. The 14 failures to parse are due to whitespace in the reference key, e.g. `PARAM ...; 6000 N REF: 0 !`, which is invalid per Thermo-Calc's database checker.

FIX: Add more TDB reference key characters

---

environment-dev.yml
setup.py

Switch conda-forge dependency to `matplotlib-base` so users aren't forced need to pull in the `pyqt` backend.
Bump matplotlib requirement to 3.3 so we can use the `loc` argument in `set_ylabel`. Closes #303.

MAINT: Switch to matplotlib-base; bump to v3.3

---

pycalphad/model.py
pycalphad/tests/test_energy.py

This PR clarifies the usage of `_MIX` models, particularly for partitioned models.
* Renames `reference_model` -> `endmember_reference_model` to be more clear about its purpose. This has potential for breakage if anyone depends on `reference_model`, but it's relatively new and I would consider it an internal API.
* Removes the `_build_reference_model` method because it's not useful enough to exist outside `endmember_reference_model`. Users could replicate the functionality by accessing `endmember_reference_model` to build it and set it to `None` to trigger a rebuild on the next access.
* Adds a warning to inform users that `endmember_reference_model` is not defined for partitioned models (after #268) and points them towards using `Model.shift_reference_state` for mixing energies with a …

MAINT: Refactor `Model.reference_model` -> `Model.endmember_reference_model`

---

.github/workflows/test.yaml
pyproject.toml
setup.cfg
setup.py

The new minimizer (#329) allowed us to drop IPOPT as a solver. All our remaining package dependencies are pure Python or have wheels shipped on PyPI (specifically, SymEngine), so installing all our dependencies from pip is now possible.
This PR:
- Changes the Github Actions scripts to use PyPA/build to build a wheel and pip to install the package
- Packages the `pycalphad.tests` package
- Uses the pytest flags `--import-mode=append` and `--pyargs pycalphad` flags to ensure that we test the installed version of the package and not the local version in the working directory.
I (accidentally) verified that we test the installed package because pytest didn't discover the tests until I packaged them in `setup.py`.
Things to consider:
1. Should we add pytest (and pytest-cov?) as runtime …

CI: Use pip and setuptools to install pycalphad instead of Anaconda

---

pycalphad/core/constants.py
pycalphad/core/equilibrium.py
pycalphad/core/minimizer.pyx
pycalphad/tests/test_equilibrium.py
pycalphad/tests/test_model.py

Fixes gh-271.
- Sets `MIN_SITE_FRACTION = 1e-16` (previously `8e-13`)
- Changes the minimum allowed composition condition to a constant, `1e-10`, instead of `1000*MIN_SITE_FRACTION` (previously `8e-10`)
- Fixes `test_degree_of_ordering` to have more significant digits of precision
- Adds `allowed_mass_residual` inside of the minimizer, which automatically adjusts the mass residual tolerance for dilute calculations

ENH/FIX: Convergence improvements for dilute case

---

pycalphad/refdata.py

This has been deprecated and raising errors when imported for four years.

MAINT: Remove `refdata.py`

---

pycalphad/tests/test_equilibrium.py

This fixes numerical differences that arise on some Windows setups (pip versus conda).

FIX: test_dilute_condition: Loosen tolerance back to 0.8.x value

---

pycalphad/core/calculate.py
pycalphad/core/equilibrium.py
pycalphad/core/utils.py
pycalphad/model.py

The rationale for this change is to remove `Phase` objects (and `Database` objects) from the core. Generally, the constituents of a `Phase` object may not be the same as the constituents of a `Model` object (they almost always are practically), so the core should use `Model` constituents so it can be decoupled from the database representation.
This is a potentially breaking change for anyone depending on this internal API.
This PR:
- Changes the API of `_sample_phase_constitution`: 
* from `_sample_phase_constitution(phase_name, phase_constituents, sublattice_dof, comps, variables, sampler, fixed_grid, pdens)`
* to `_sample_phase_constitution(model, sampler, fixed_grid, pdens)`
- Documents `Model.constituents` as a step towards making the public API of `Model` objects better defined.
- …

MAINT:  Refactor _sample_phase_constitution

---

pycalphad/core/lower_convex_hull.py

Fixes a sorting bug introduced into `lower_convex_hull` by #329. We used to rely on `indep_conds` for sorting the state variables, but now we use the `state_variables` variable directly and `indep_conds` is dead code.
This PR sorts the `state_variables` now.

FIX: potential sorting bug in lower_convex_hull

---

pycalphad/model.py

This makes a significant performance difference for multicomponent models with magnetism.

ENH: Model: Change some uses of subs to symbol_replace for performance

---

.github/workflows/docs.yaml
docs/api/pycalphad.core.rst
docs/api/pycalphad.rst
docs/conf.py

- Sphinx `conf.py`: Don't load the version from a hardcoded `_version.py` (changes from #341)
- CI: Build (but don't deploy) documentation on pull requests so we can catch regressions in the docs in the future
- CI: Use pip to install rather than conda in docs builds

DOC/BLD: Fix documentation builds

---

pycalphad/core/minimizer.pyx

The `new_free_stable_compset_indices` are created after phase removal [here](https://github.com/pycalphad/pycalphad/blob/657f5ba38ef582573a31cf6646ea5528286db83b/pycalphad/core/minimizer.pyx#L816), but these new stable indices with the phases removed are essentially reset [here](https://github.com/pycalphad/pycalphad/blob/657f5ba38ef582573a31cf6646ea5528286db83b/pycalphad/core/minimizer.pyx#L841) (by the code removed in this change).
This is just one way to address this issue, maybe the most straightforward? An alternative could be set the phase amounts to the phases scheduled for removal to zero and to leave in the code that reconstructs the `new_stable_compset_indices` (which won't include the phases with new zero phase amounts).
The removed code could also fix a bug where a fixed phase …

FIX: Minimizer: CompositionSet objects set for removal are not removed

---

.gitignore
pycalphad/core/constants.py
pycalphad/tests/test_equilibrium.py
pycalphad/tests/test_model.py

- Change `MIN_SITE_FRACTION` to `1e-14`
- Add a test to confirm the high-temperature jitter in Al-Ni is fixed by the change (was checked before and after)
- Adjust `test_degree_of_ordering` tolerance to account for sensitivity of our degree-of-ordering metric to differences in `MIN_SITE_FRACTION`
- Add a test to close gh-259
- Add Windows compiled extension type `.pyd` to `.gitignore`

FIX/TST: Adjust MIN_SITE_FRACTION and add tests

---

environment-dev.yml
pycalphad/io/tdb.py
setup.py

Fixes gh-347, which reports a regression with the pyparsing 3.0 pre-release. This change should be backwards compatible with pyparsing 2.4+. I do not know the precise root cause of the regression, as I was able to narrow the problem down empirically. My best guess is that the semantics of `pyparsing.White()` have changed in some way.
@bocklund This should be run against your private collection of TDBs to identify regressions.
Checklist

FIX: pyparsing 3.0 support

---

.github/workflows/test.yaml

The source code needs to be checked out when uploading coverage.

CI: Checkout the repo to fix coverage

---

pycalphad/io/tdb_keywords.py

This PR adds support for parameters supported by Thermo-Calc as of the 2021b documentation set.
Notably, `VA`, `VC` and `VK` molar volume parameters were added and some property model parameters were added (new in the Thermo-Calc 2021b documentation).
None of the new parameters affect the Gibbs energy, so we should still remain at feature parity with the energy contributions of Thermo-Calc. The new property model parameters don't have model implementations yet, but this may open the door for an interested user.

ENH: Add support for all TC parameters as of 2021b documentation

---

pycalphad/core/eqsolver.pyx
pycalphad/core/minimizer.pyx
pycalphad/plot/binary/map.py

I have noticed in benchmarking that roughly 1/3 of the time in the solver is spent performing this copy operation on the `state`. We don't do anything meaningful with the old state except for using its data, so I propose to remove it and replace the couple instances with explicitly storing the relevant variables before taking a step.
If we want to do more advanced things with the previous state(s) later, that's definitely something we could do, but I think all the memory allocations in one of the innermost loops is probably not worth it compared to copying the values we need out.
This change could probably use a more real benchmark to justify it, but I wanted to get it posted for feedback before I invest much more time into it.

ENH: Refactor solver and improve solver performance

---

pycalphad/codegen/callables.py
pycalphad/core/calculate.py
pycalphad/core/equilibrium.py
pycalphad/core/utils.py
pycalphad/tests/test_calculate.py
pycalphad/tests/test_codegen.py
pycalphad/tests/test_equilibrium.py

Changes:
- `build_phase_records`
- Defaults to build derivatives of the output. This is the more common case and SymEngine makes the compilation fast enough that's it's not as much of a burden to build them by default.
- The `comps` argument now accepts string components or `Species` objects via `unpack_components`. Before this change, only `Species` objects were allowed.
- `calculate` and `equilibrium`
- Accept the `phase_records` keyword argument 
- The `callables` keyword argument is used if the phase records are constructed. If the `phase_records` argument is supplied by the caller, the `callables` argument is ignored.
- `equilibrium` passes `phase_records` down to `calculate` instead of rebuilding them in `calculate`
- Both functions check that all the active phases have entries in …

ENH: Allow passing dictionaries of PhaseRecord objects to equilibrium and calculate

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

Updated the database string to always be parsed to uppercase. Also passed the test cases mentioned in the issue #359

FIX: Database parsing fails if some tokens are not uppercase

---

pycalphad/codegen/callables.py
pycalphad/core/minimizer.pyx

This PR makes two small improvements to better support the use of custom state variable objects.
One change silences a callables warning that would occur every time a custom state variable was used; this has been improved to only warn when expected state variables are _missing_. The other change relaxes an implicit assumption / bug that state variables would never be equal to zero (when calculating a percent change in value); now we detect this case and switch to an absolute difference.

FIX: Improved custom state variable support

---

pycalphad/core/calculate.py
pycalphad/tests/test_equilibrium.py

FIX: calculate: Phase index offset for associate models

---

pycalphad/core/minimizer.pyx

This PR contains 3 changes to the minimizer:
1. The `take_step` function is replaced with two functions to solve the equilibrium matrix and extract the chemical potentials (`solve_state`) and to take the step with the corrections in the phase amounts, state variables, and site fractions (`advance_state`). The `extract_equilibrium_solution` function is also now a part of `advance_state`. This refactor keeps the logic for advancing the state separate and contained in one function. 
2. The convergence criterion has been changed to converge based on changes in phase amounts, state variables, and site fractions, instead of depending on mass residual and/or chemical potential changes. The rationale being that if the phase amounts, state variables, and site fractions aren’t changing, the other …

ENH: Minimizer: refactor and convergence improvements

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

This fixes two bugs related to writing TDB files and reflowing lines:
1. Fixes a bug in `reflow_text` where lines that are too long and contain no valid linebreak characters would result in an infinite loop of finding the same `linebreak_idx` and emitting the same line until running out of memory. Now lines that cannot be reflowed to under the `linewidth` raises an error.
2. Adds a whitespace to the delimiter between species in the `CONSTITUENTS` line (it's now `, ` instead of `,`) so `reflow_text` can reflow the line at any element. This fixes a bug where phases with many constituents would trigger the infinite loop (and now error) from (1).
A test is added for each case.

FIX: Fix TDB line length bugs

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

Fixes gh-399.
- TCPrinter: Remove check for non-integer exponent of power operator, which is probably unnecessary
- TCPrinter: Special-case printing of exponential function, which is represented as `e**x` in SymEngine
This was a regression from gh-376. This PR includes a test for the fixed behavior.

FIX: TCPrinter: Special-case printing for exponential function

---

pycalphad/io/cs_dat.py
pycalphad/io/tdb.py

- Floating point Gibbs energy exponents (for fixed T/P terms) for read-write equality comparison support
- Use Database.add_structure_entry
- Use phase "BLANK" instead of None (needs a string for type stability) and "BLANK" is consistent with how pycalphad treats TDBs
- Use a global default minimum temperature for piecewise intervals of 0.01 K, in agreement with how we handle TDBs
- Some DAT files have two temperature intervals in a row with the same upper limit. I am interpreting that as an implication that the function should extrapolate beyond that point, so we choose a default upper limit of 10000 K, in agreement with TDBs
- Fix a bug in magnetic parameters: `BMAG` should have been `BMAGN`.
- Improve error messages for `pycalphad.io.tdb.to_interval` that users may find more helpful …

BUG: Changes to the ChemSage DAT parser to be more consistent with the TDB parser

---

pycalphad/core/minimizer.pyx

This PR moves `advance_state` to be the last step in the minimization loop. 
The main reason to make this change is that we want the chemical potentials that we get from `solve_state` to be consistent with the current site fractions, phase amounts, and state variables when we check for convergence, change phases, and return a solution. Right now, we apply the corrections to site fractions, phase amounts, and state variables after solving for the chemical potentials with the current values, so they are effectively one step ahead of the chemical potentials. 
This fixes #372 as the driving forces should now always be zero in `change_phases`, as the chemical potentials are now consistent with the current site fractions. 
Summary of changes:
1. If the phases change, we don't advance the state. …

FIX: Make minimizer state more internally consistent

---

pycalphad/codegen/sympydiff_utils.py
pycalphad/core/lower_convex_hull.py

These are some small fixes which enable compatibility with the WebAssembly-based [pyodide](https://pyodide.org/en/stable/ ) Python distribution. The changes here will only affect environments where (a) SymEngine is compiled without LLVM support (like Pyodide); or (b) the platform is 32-bit.
All officially supported platforms for pycalphad have been 64-bit for a while, so both of these changes are backward compatible. In addition, they are also forward compatible if LLVM support for SymEngine in pyodide is enabled, or (unlikely in the short term) pyodide adds wasm64 support.

ENH: Compatibility fixes for pyodide

---

pycalphad/core/minimizer.pxd
pycalphad/core/minimizer.pyx

Profiling-guided removal of (relatively) expensive NumPy calls
With a couple ternary benchmark systems, I'm seeing a consistent 2x speedup in the `run_loop` time and almost all the profiled code that drops back into Python (from Cython) is gone.
Summary of changes:
1. Don't recompute ALLOWED_MASS_RESIDUAL on the hot loop. We can compute it in the initializer if we assume the prescribed elemental amounts is constant
2. Replace `np.sum` with manually computed phase composition sums in SystemState initializer and recompute()
3. Replace `np.all` call in consolidation check for remove_and_consolidate_phases
4. Replace `np.take`, `np.nonzero`, `np.argsort` with loopy equivalents (this is less of a speedup, but we probably just hit this code path less in the benchmark and in practice)
The intent …

ENH: minimizer performance improvements

---

pycalphad/core/hyperplane.pyx
pycalphad/tests/databases/crtiv_ghosh.tdb
pycalphad/tests/test_equilibrium.py

FIX: hyperplane: Incorrectly throwing out stable starting points

---

pycalphad/model.py
pycalphad/tests/test_calculate.py

This PR is a partial implementation of the molar volume model from [Lu, Selleby, and Sundman (2005)](https://doi.org/10.1016/j.calphad.2005.04.001). It includes the nonmagnetic thermal expansion, magnetic contribution to molar volume, and the contribution to the Gibbs free energy in cases where the molar volume is independent of pressure. Tests for these terms are also included. There are no required changes to the dependencies of pycalphad. This PR is inclusive of PR #423.
The pressure dependence of the molar volume can be implemented in the future via VC and VK parameters and Equations 9, 10, and 12 of the reference paper. It will require the exponential integral to be implemented into symengine.

ENH: Molar volume

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

In ThermoCalc, the IF/THEN keywords in the TYPE_DEFINITION provides a way to run commands during database loading based off the elements selected. This typically is used for adding a composition set to help with miscibility gap detection or rejecting/restoring phases (though adding composition sets seems more common). Pycalphad detects miscibility gaps based off the sampling strategy and the rejecting/restoring phases may reduce transparency of the database to the users.
In pycalphad, the tdb parser assumes that the TYPE_DEFINITION command is used for disordered or magnetic contributions, in which the parser can fail if the command is not one of those two. This pull request will ignore any TYPE_DEFINITION that has an IF/THEN keyword and give a warning that parsing these keywords is …

FIX: ignoring IF/THEN statements in TYPE_DEFINITION keywords

---

pycalphad/variables.py

The [README](https://github.com/pycalphad/pycalphad/tree/d4dd6c91e4215c0dc84bc2e89af00cd92210a708#readme) states "Unsolicited pull requests are _happily_ accepted!"
Here's an unsolicited pull request that fixes issue #319 
```python
>>> import pycalphad.variables as v
>>> repr(v.Species(None))
'Species(None)'
>>> repr(v.Species('*'))
"Species('*')"
```

FIX: misleading __repr__ for Species(None) and Species('*')

---

.devcontainer/devcontainer.json
.vscode/settings.json
.vscode/tasks.json

This adds support for [Development Containers (devcontainers)](https://containers.dev/) to the pycalphad repository. This makes it easy to use [GitHub Codespaces](https://github.com/features/codespaces) and [Visual Studio Code](https://code.visualstudio.com/) with the [Dev Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to get access to a working development environment, which is convenient for on-the-go PR review and onboarding new developers.
For Visual Studio Code users (cloud or local), a config file is added that adds the pycalphad Cython build step as the default build task (accessible with Ctrl+Shift+B, by default).

BLD: Add devcontainer/vscode support

---

setup.py

Relaxes the symengine version pin so that future symengine releases also satisfy the dependency requirement. SymEngine release cadence has increased and we're also seeing fewer regressions, so I think it's safe and advisable for pycalphad to relax the hard pin. Also, this will fix #497.
Checklist

MAINT/FIX: Relax version pin for symengine

---

pycalphad/model.py

- Fix normalization of molar volume energy and properties to be per mole of atoms
- Set molar volume properties (`V0`, `VA`, `VK`, `VC`) as attributes of `Model`. Not sure about `VK` and `VC` parameter normalization, but for now I'm assuming they are the same normalization `VA` (parameters stored per mole of atoms, rather than the usual per mole of formula)
- Set the property name of molar volume to be `VM`, rather than `MV`, which is more consistent with commercial software and handling molar quantities
- Replace molar volume property expressions with symbols in the database. If we don't do this, any `FUNCTION` TDB keywords (which become symbols) get set to zero when computing in `calculate` or `equilibrium`

FIX: Molar volume model fixes

---

.github/workflows/test.yaml
docs/conf.py
pycalphad/__init__.py
requirements-dev.txt
setup.py

- Add support in CI for Python 3.12
- Drop support for Python 3.7 as it's EOL as of June 2023 https://devguide.python.org/versions/
- Drop a really old pin on furo because we can upgrade now (pin was forcing old sphinx versions to be installed, which is what was breaking our docs builds in CI)
- Fixes for new versions of sphix:
1. Language is no longer allowed to be `None`, set to `'en'` which is the default
2. Fix extlinks that requires a `%s` in the caption (added support for that in v4.0, removed support for deprecated way without the `%s` in v6.0 https://github.com/sphinx-doc/sphinx/pull/10471)

MAINT/BLD: Python CI support and docs build fixes 

---

.github/workflows/deploy.yaml

This PR adds support for [trusted publishing](https://docs.pypi.org/trusted-publishers/) on PyPI using GitHub Actions as an OpenID Connect provider. I have already performed the setup on the PyPI side to allow for this.
After this is merged, we can revoke the dedicated PyPI upload token for pycalphad and use GitHub Actions as our sole deployment tool. We already do this, but this will prevent a leaked token from being able to manipulate release artifacts out-of-band.

BLD: deploy.yaml: PyPI trusted publisher support

---

pycalphad/core/calculate.py
pycalphad/core/eqsolver.pyx
pycalphad/core/halton.py
pycalphad/core/utils.py
pycalphad/model.py
pycalphad/tests/test_energy.py
pyproject.toml
requirements-dev.txt

Adds build-time and runtime support for NumPy 2.0. This version is C-API compatible with NumPy 1.x, so we set a build-time requirement for >=2.0 while retaining support for 1.x. This compatibility guarantee allows us to deprecate the usage of `oldest-supported-numpy` per the recommendation of those authors.
NumPy 2.0 does not support Python 3.8, but these changes do not directly impact our ability to support py38 on NumPy 1.x. (It is probably overdue for pycalphad to drop py38 support, but that can be done separately from here.)
Two minor and backwards-compatible fixes for runtime are needed and also added here: `np.float_` is renamed to `np.float64` and `np.complex_` is renamed to `np.complex128`. (Complex number arrays are used for certain tests.)
See also:
- …

MAINT/BLD: NumPy 2.0 Support

---

.github/workflows/deploy.yaml

`macos-11` is deprecated in GHA so this is probably a good time to bump all the OS versions for the `deploy.yaml` workflow. I've also removed a now-unused cibuildwheel version from `CIBW_SKIP` for good measure.
Checklist

MAINT/BLD: Bump OS versions for wheel build/deploy workflow

---

.github/workflows/deploy.yaml

Set fetch-depth to zero to guarantee version tags are picked up from SCM in sdist workflow

FIX/BLD: Correct version specifier in sdist building workflow

---

.github/workflows/deploy.yaml
pycalphad/_dev/__init__.py
pyproject.toml

Removes local version specifier (`+hash`) from CI builds to allow for upload of artifacts to TestPyPI. Follows the strategy outlined in https://github.com/pypa/setuptools_scm/issues/455#issue-634969642
Checklist

BLD/CI: Remove local version specifier for TestPyPI uploads

---

.github/workflows/deploy.yaml

This PR drops dedicated macOS `universal2` wheel building in cibuildwheel. (We continue to build `x86_64` and `arm64` wheels for macOS.) The reasons for this are:
1. Our [upstream](https://github.com/numpy/numpy/pull/20787) isn't building them, so users will never automatically select this wheel during installation.
2. It is straightforward for downstream packagers (using `py2app` or other solutions) to fuse single-arch wheels into universal wheels themselves: ` pip install delocate ; delocate-fuse $amd64_wheel $arm64_wheel -w .`
3. The consensus seems to be that shipping single-arch wheels and letting downstream manually fuse them is the way to go. ( e.g. https://github.com/pypa/cibuildwheel/issues/705 and https://github.com/python-pillow/pillow-wheels/issues/359 ).
4. On pycalphad CI, …

ENH/BLD: Drop dedicated macOS universal wheel builds

---

pycalphad/model.py

Changes the error message for mismatched disordered and ordered sublattices from this:
```
ValueError: Number of interstitial sublattices for the disordered phase (1) and the ordered phase (5) do not match. Got substitutional sublattice indices of [].
```
to this:
```
ValueError: Number of interstitial sublattices for the disordered phase FCC_A1 (1) and the ordered phase GP_MAT (5) do not match. Found substitutional sublattices in the ordered phase with indices of []. Ensure that all the constituents in the substitutional sublattices for the disordered and ordered phase match exactly and the constituents in the interstitial sublattices for the disordered and ordered phase match exactly.
```

ENH: Improve error message for ordering models having mismatched constituents

---

pycalphad/io/database.py
pycalphad/tests/fixtures.py
pycalphad/tests/test_database.py

Enables the following behavior:
```python
from pathlib import Path
from pycalphad import Workspace
wks = Workspace()
wks.database = Path("dat/Fe-C.dat")
```
Closes #544 
We test this by changing the tests that usually wrap `files()` output (a `PosixPath`) in a `str()` to make a string-like path. We remove this behavior in several tests.
This also changes some tests (`test_unspecified_format_from_string` and `test_unspecified_format_from_file`) to be more in line with what I interpreted to be the spirit of the tests: passing database strings (not strings for the paths to the databases) to `Database.from_string` or `Database.from_file` should fail if a format is not specified.

Add pathlib support to Database reading

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

This PR will make TDBs correctly export when expressions with nested powers (e.g., `a**x**y`) are in the TDB.
Example:
```python
from pycalphad import Database
dbf = Database("""
ELEMENT A FCC_A1 0 0 0 !
PHASE FCC_A1 % 1 1 !
CONSTITUENT FCC_A1 : A : !
PARAMETER G(FCC_A1,A;0) 1 ((3.49 * (1373 * T**(-1)))**(1.778 * (1473 * T**(-1))))**(0.926); 10000 N !
"""
)
print(dbf.to_string(fmt='tdb'))
```
Current Behavior (Wrong, truncating the non-integer exponent):
```
$ [snip]
PARAMETER G(FCC_A1,A;0) 1.0 ( 4791.77*T**(-1) )**(2618.994*T**(-1))**(0);
10000.0 N !
```
New Behavior (Correct):
```
$ [snip]
PARAMETER G(FCC_A1,A;0) 1.0 ( ( 4791.77*T**(-1) )**(2618.994*T**(-1))
)**(0.926); 10000.0 N !
```
In addition, the behavior for non-integer exponents is now controllable via the `if_incompatible` …

FIX: tdb: Export TDB with nested powers and non-integer exponents

---

pycalphad/core/phase_rec.pyx

This PR moves `FastFunctionFactory.getfunc()` out of a tight loop inside of `PhaseRecord.prop_2d()`. Despite hitting the cache, it seems that `getfunc()` takes appreciable time and, for large numbers of inputs (`num_imps`), it can become as much as 40% of the runtime of that function. For large values of `pdens` (such as the value 500, used by default inside of mapping), this significantly impacts the `calculate` function.
On my laptop, this change shaves a few seconds off the mapping tests.

ENH: Mapping: Small performance fix

---

pycalphad/io/tdb.py
pycalphad/tests/test_database.py

In the TDB parser, the pyparsing grammar only sees one command-delimited (`!`-delimited) line at a time. In the event of a parser exception, the error reporting metadata incorrectly returns a line number of 1.
This PR modifies the `ParseException` object raised by the parser to refer to the (almost) original input text. We also take the opportunity to shorten the error message returned by the string representation of the object. To ensure the column number printed in the error message aligns with the input text, we remove some pre-processing of the text where whitespace was stripped (the pyparsing grammar for TDB already skips whitespace).
```python
from pycalphad import Database
Database("""     PARAMETER G(BCC,FE:H;0) 298.15  +GHSERFE+1.5*GHSERHH
+258000-3170*T+498*T*LN(T)-0.275*T**2; …
```

ENH: tdb: ParseException returns correct line numbers

---

pycalphad/core/workspace.py
pycalphad/tests/test_workspace.py
pycalphad/variables.py

Fixes the following cases with a test:
- Fixes wildcard expansion on components (for properties without a sublattice index) to expand on non-vacant pure elements. With proper component support, we would go back to using `self.components`, but currently `self.components` contain all phase constituents, including, for example, vacancies
- Adds `expand_wildcard` on components for chemical potentials
- Fixes wildcard expansion for properties where expansions are on phase constituents, such as site fractions
- Adds support for wildcard expansion on sublattice indices (required adding `sublattice index = '*'` as valid).
- Change behavior of compute_property for site fractions to return NaN if the phase is not stable (previously we were returning zero)

FIX: fix wildcard support

---

pycalphad/codegen/phase_record_factory.py
pycalphad/core/conditions.py
pycalphad/core/eqsolver.pyx
pycalphad/core/lower_convex_hull.py
pycalphad/core/solver.py
pycalphad/core/utils.py
pycalphad/core/workspace.py
pycalphad/property_framework/metaproperties.py
pycalphad/tests/test_workspace.py
setup.py

This PR changes how Workspace objects are initialized, to ensure that each attribute is initialized after its dependencies (`database` before `models`, `parameters` before `phase_record_factory`, etc). It also suspends dependency callbacks inside of `Workspace.__init__` to avoid calls to the `default_factory` of attributes that will be overwritten again later in initialization.
For the worst case of a user passing in fully-initialized attributes to the constructor of a Workspace object, with pre-computed `models` and `phase_record_factory` (a common case inside of ESPEI and any other software calling pycalphad in a high-throughput loop), this PR should substantially improve performance.
We can be a little smarter still, by eliding dependency updates for cases where the change in the …

ENH: Workspace: Suspend attribute dependency updates during init

---

pycalphad/tests/test_equilibrium.py
pycalphad/tests/test_workspace.py

- Fixes the test names and descriptions of two tests related to #503 
- For [`test_issue_503_suspend_phase_infeasible_internal_constraints`](https://github.com/pycalphad/pycalphad/pull/561/files#diff-31e23fd0f866a3d4f331e4bd2bfa4840923e1f047fb204497622e549367b0cbcR328-R329): The behavior we are testing for does not require that we set a mole fraction to 1, so we change that as well. There's still an issue with the minimizer non-deterministically failing near the edge of composition space, but this test does not capture that behavior consistently enough to be useful, so we side-step the issue for now.
For that issue we ended up adding two sets of fixes because there were really two issues:
1. In [`test_issue_503_charged_infeasible_subsystem`](https://github.com/pycalphad/pycalphad/pull/561/ …

TST: Revise ambiguous test description and conditions

---

pycalphad/codegen/phase_record_factory.py
pycalphad/core/calculate.py
pycalphad/core/utils.py
pycalphad/core/workspace.py
pycalphad/mapping/strategy/strategy_base.py
pycalphad/model.py
pycalphad/models/model_mqmqa.py
pycalphad/plot/binary/map.py
pycalphad/tests/test_utils.py
pycalphad/tests/test_variables.py
pycalphad/tests/test_workspace.py
pycalphad/variables.py

This PR sets the groundwork for more formally distinguishing a `Component` from a `Species`. It is breaking for the public API of Workspace, and consumers of the private API for `pycalphad.core.utils.unpack_components`. We are making these breaking changes now, so future changes that implement generalized (non-pure-element) component support can be non-breaking or minimally breaking in public APIs.
The following changes are made:
1. Add `v.Component` class. This is similar to `Species`, but distinct because 1) `Species` are reserved to refer to phase constituents, and 2) `Species` are allowed to have charges
2. Rename `pycalphad.core.utils.unpack_components` to `unpack_species` to be more accurate
3. Add a `v.unpack_components` function to process components following documented rules …

ENH: Add Component implementation in variables

---

pycalphad/core/workspace.py
pycalphad/tests/test_workspace.py

Adds a default constructor for `Workspace.database`, which fixes assumptions other attribute code is making about `wks.database` not being None.

FIX: Workspace: Allow empty object creation

---

pycalphad/codegen/sympydiff_utils.py
pycalphad/io/tdb.py
pycalphad/tests/test_database.py

A recent [change in pyparsing ](https://github.com/pyparsing/pyparsing/pull/571) added caching to attributes on ParseException objects using the `cached_property` decorator. Those caches are not invalidated when the `pstr` and `loc` for the ParseException objects are modified (as we do, to provide more accurate line numbers, since #550 ).
The caches for these properties are stored as attributes on the instances with the same name as the property, so it is easy to clear the cache using `obj.__dict__.pop('property_name', None)`. This is backwards-compatible since it's a no-op on previous versions of pyparsing, where only the `property` decorator is present. Details of how this works can be found in the [answers to this StackOverflow …

FIX: ParseException handling in pyparsing 3.2.0

---

pycalphad/core/phase_rec.pyx
pycalphad/model.py
pycalphad/tests/test_energy.py
pycalphad/tests/test_model.py

This pull request implements the composition dependent reciprocal parameter as defined in eq 5.99 in:
H.L. Lukas, S.G. Fries, B. Sundman, "Computational Thermodynamics - The Calphad Method, Ch 5. Models for the Gibbs Free Energy, 5.8 Modeling using sublattices, 5.8.1. Reciprocal solutions, 5.8.1.1. Excess Gibbs energy for the reciprocal solution" Cambridge University Press 2007. ISBN: 978-0-521-86811-2
For excess mixing in a reciprocal solution:
```math
^E G_m = y_A^0 y_B^0 y_C^1 L_{AB:C} + y_A^0 y_B^0 y_D^1 L_{AB:D} + y_A^0 y_C^1 y_D^1 L_{A:CD} + y_B^0 y_C^1 y_D^1 L_{B:CD} + y_A^0 y_B^0 y_C^1 y_D^1 L_{AB:CD}
```
The ternary terms are defined by with a Redlich-Kister polynomial, but the reciprocal parameter can be defined as the following the include composition dependency:
```math …
```

High order reciprocal model

---

pycalphad/codegen/sympydiff_utils.py
pycalphad/tests/test_codegen.py

In PyCalphad we eventually represent all our exponents as floating points, even if they are actually integer values. This becomes troublesome because SymEngine evaluates small, negligible imaginary parts, as in the following example:
```python
from sympy import Symbol
x = Symbol("x")
print((x**(2.0)).subs({x: -1})) 
from symengine import Symbol
x = Symbol("x")
print((x**(2)).subs({x: -1})) 
print((x**(2.0)).subs({x: -1})) 
```
In this case, the imaginary part is not useful and causes an issue when we call `lambdify` in (`build_functions`) with the default argument that `real=True`. We probably haven't run into this before because our bases are typically symbolic (e.g. `T` in power functions) and these are typically not evaluated to a complex number until the function is actually evaluated …

FIX: Fix lambdifying models that evaluate to have complex numbers

---

.github/workflows/deploy.yaml
.github/workflows/test.yaml
ONBOARDING.rst
pycalphad/tests/test_equilibrium.py
pyproject.toml
setup.py

Dropping 3.9 in accordance with [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html)

MAINT: Bump minimum Python version to 3.13, drop 3.9; test and dependency fixes

---

pycalphad/property_framework/units.py
pycalphad/tests/test_workspace.py
setup.py

Fixes #609
Also fixed a runtime issue on Windows + MinGW (missing static libs), in a separate commit -- feel free to drop it.  
https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html#python-3-8

FIX: avoid ZeroDivisionError on converting units
